// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: v1/captcha.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetCaptcha with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetCaptcha) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCaptcha with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetCaptchaMultiError, or
// nil if none found.
func (m *GetCaptcha) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCaptcha) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetCaptchaMultiError(errors)
	}

	return nil
}

// GetCaptchaMultiError is an error wrapping multiple validation errors
// returned by GetCaptcha.ValidateAll() if the designated constraints aren't met.
type GetCaptchaMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCaptchaMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCaptchaMultiError) AllErrors() []error { return m }

// GetCaptchaValidationError is the validation error returned by
// GetCaptcha.Validate if the designated constraints aren't met.
type GetCaptchaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCaptchaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCaptchaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCaptchaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCaptchaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCaptchaValidationError) ErrorName() string { return "GetCaptchaValidationError" }

// Error satisfies the builtin error interface
func (e GetCaptchaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCaptcha.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCaptchaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCaptchaValidationError{}

// Validate checks the field values on GetCaptchaReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetCaptchaReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCaptchaReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCaptchaReplyMultiError, or nil if none found.
func (m *GetCaptchaReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCaptchaReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for B64

	// no validation rules for Tb64

	// no validation rules for Cid

	if len(errors) > 0 {
		return GetCaptchaReplyMultiError(errors)
	}

	return nil
}

// GetCaptchaReplyMultiError is an error wrapping multiple validation errors
// returned by GetCaptchaReply.ValidateAll() if the designated constraints
// aren't met.
type GetCaptchaReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCaptchaReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCaptchaReplyMultiError) AllErrors() []error { return m }

// GetCaptchaReplyValidationError is the validation error returned by
// GetCaptchaReply.Validate if the designated constraints aren't met.
type GetCaptchaReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCaptchaReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCaptchaReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCaptchaReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCaptchaReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCaptchaReplyValidationError) ErrorName() string { return "GetCaptchaReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetCaptchaReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCaptchaReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCaptchaReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCaptchaReplyValidationError{}

// Validate checks the field values on VerifyCaptcha with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *VerifyCaptcha) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VerifyCaptcha with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in VerifyCaptchaMultiError, or
// nil if none found.
func (m *VerifyCaptcha) ValidateAll() error {
	return m.validate(true)
}

func (m *VerifyCaptcha) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Cid

	// no validation rules for VerifyValue

	if len(errors) > 0 {
		return VerifyCaptchaMultiError(errors)
	}

	return nil
}

// VerifyCaptchaMultiError is an error wrapping multiple validation errors
// returned by VerifyCaptcha.ValidateAll() if the designated constraints
// aren't met.
type VerifyCaptchaMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VerifyCaptchaMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VerifyCaptchaMultiError) AllErrors() []error { return m }

// VerifyCaptchaValidationError is the validation error returned by
// VerifyCaptcha.Validate if the designated constraints aren't met.
type VerifyCaptchaValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifyCaptchaValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifyCaptchaValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifyCaptchaValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifyCaptchaValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifyCaptchaValidationError) ErrorName() string { return "VerifyCaptchaValidationError" }

// Error satisfies the builtin error interface
func (e VerifyCaptchaValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifyCaptcha.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifyCaptchaValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifyCaptchaValidationError{}

// Validate checks the field values on VerifyCaptchaReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *VerifyCaptchaReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on VerifyCaptchaReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// VerifyCaptchaReplyMultiError, or nil if none found.
func (m *VerifyCaptchaReply) ValidateAll() error {
	return m.validate(true)
}

func (m *VerifyCaptchaReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Message

	// no validation rules for Code

	if len(errors) > 0 {
		return VerifyCaptchaReplyMultiError(errors)
	}

	return nil
}

// VerifyCaptchaReplyMultiError is an error wrapping multiple validation errors
// returned by VerifyCaptchaReply.ValidateAll() if the designated constraints
// aren't met.
type VerifyCaptchaReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m VerifyCaptchaReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m VerifyCaptchaReplyMultiError) AllErrors() []error { return m }

// VerifyCaptchaReplyValidationError is the validation error returned by
// VerifyCaptchaReply.Validate if the designated constraints aren't met.
type VerifyCaptchaReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e VerifyCaptchaReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e VerifyCaptchaReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e VerifyCaptchaReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e VerifyCaptchaReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e VerifyCaptchaReplyValidationError) ErrorName() string {
	return "VerifyCaptchaReplyValidationError"
}

// Error satisfies the builtin error interface
func (e VerifyCaptchaReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sVerifyCaptchaReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = VerifyCaptchaReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = VerifyCaptchaReplyValidationError{}
